### PR TITLE
whatwedohere improvements

### PR DESCRIPTION
**Pull request by lucasmauricio**
**Content**: I rewrote to say what we are now and what we aim to do. I removed the text that overstates project's status.
**Technical**: I separated the text and presentation, putting text into a yml file and generalized its output.
Task: WEB-15

### CODE REVIEW

**Review by igordias — CHANGES_REQUESTED** [review]
1. Regarding the text per se:
1.1. I'd remove that determiner* before "science": "Leading science and academic industry [...]" sounds better. Also, note that I've removed the "s" in "academic", as it's supposed to be an adjective here, not a noun, correct? 

1.2. "Résumés" has an accent on the first "e" too (at least in french). 

1.3. The sentence "We are researches but it's for everyone." doesn't quite make sense to me. There is a "r" missing in "researchers", also, in which way would us being researchers keep anyone from doing so? I'd recommend using "We are researchers, and so can be anyone." instead, or simply replacing "but" by "and" in the original sentence: "We are researchers and it's for everyone".

1.4. I also recommend removing the 2nd determiner in "We want to enable the integration between the IoT's specific plaforms.": "We want to enable the integration between IoT's specific platforms".

1.5. "Working on connectivity ways" sounds weird, I think you meant "Working on connective ways". (connectivity = noun, connective = adjective).

1.6. I think "to make possible devices reach out the internet" won't express what you mean, it should be "to make it possible for devices to reach out the internet", "possible devices" makes "possible" sound like an adjective, "make it possible for" shows expressively that "possible" here is used as a verb.

1.7. "several kind of devices" should be "several kinds of devices".

2. Regarding the html:
I'd remove tags 'center' and 'i' from the code as 'center' is not recommended at all by W3C, and 'i' in this case doesn't play a semantic role. Positioning elements on the page should be done only by css.
PS: I recommend start validating every HTML code with https://validator.w3.org/ from now.

**Comment by lucasmauricio** [comment]
great issues @IgorDias. I'll take a look at your suggestions. Thanks

**Comment by lucasmauricio** [comment]
@IgorDias, I did a text review on your suggestions and used external css to put text decoration. Is it ok to you or do you have anything different in mind?

**Comment by ovflowd** [comment]
Amazing what is being done here! I love this team 😍

**Comment by igordias** [comment]
@lucasmauricio sounds good, HTML looks perfect now! However, I just notice that the text in these last commits weren't updated. Can you please check my commit here ( https://github.com/uiot/uiot.github.io/pull/18/commits/7a5b54cf6615efa30b9618bda106455357d31ec2 ) and apply your changes by using that as the model?

**Pull request merged**
